"""Initial migration

Revision ID: e1e93d291a30
Revises: 
Create Date: 2025-06-21 15:24:31.161193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1e93d291a30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('middle_name', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('required_volunteers', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(length=128), nullable=False),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('contact_info', sa.String(length=128), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['volunteer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    # Добавляем роли
    op.execute("INSERT INTO roles (name, description) VALUES ('admin', 'Администратор')")
    op.execute("INSERT INTO roles (name, description) VALUES ('moderator', 'Модератор')")
    op.execute("INSERT INTO roles (name, description) VALUES ('user', 'Пользователь')")

    # Получаем id роли user
    conn = op.get_bind()
    user_role_id = conn.execute(sa.text("SELECT id FROM roles WHERE name='user'")).scalar()

    # Добавляем пользователя
    op.execute(
        f"""
        INSERT INTO users (username, password, last_name, first_name, middle_name, role_id)
        VALUES (
            'testuser',
            'scrypt:32768:8:1$f8eaOxEFe2YxuYHO$3bb1d2c5eba11a20b5790cf32aee173961514fba8a833245a3df785fdc1ce5e4565e62fe1d109cb416564fbfddc850fc15659d30ed7f58184fd201f78a793dbf',
            'Иванов',
            'Иван',
            'Иванович',
            {user_role_id}
        )
        """
    )
    # ### end Alembic commands ###


def downgrade():
    op.execute("DELETE FROM users WHERE username='testuser'")
    op.execute("DELETE FROM roles WHERE name IN ('admin', 'moderator', 'user')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registrations')
    op.drop_table('events')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
